---    

- name: apt update
  shell: apt update

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/jenkins/myDir
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/nathanforester/BirthDateAppFlask.git
    dest: /home/ubuntu/myDir/
